---
- name: Download WordPress  
  get_url: 
    url=https://wordpress.org/latest.tar.gz 
    dest=/tmp/wordpress.tar.gz
    validate_certs=no

- name: Extract WordPress  
  unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/ copy=no
  sudo: yes

- name: Update default Apache site
  sudo: yes
  lineinfile: 
    dest=/etc/apache2/sites-enabled/000-default.conf 
    regexp="(.)+DocumentRoot /var/www/html"
    line="DocumentRoot /var/www/wordpress"
  notify:
    - restart apache

- name: Copy sample config file
  command: mv /var/www/wordpress/wp-config-sample.php /var/www/wordpress/wp-config.php creates=/var/www/wordpress/wp-config.php
  sudo: yes

- name: Create upload folder
  file: path=/var/www/wordpress/wp-content/uploads  state=directory mode=0755 owner=www-data

- name: Update WordPress config file
  replace:
    dest=/var/www/wordpress/wp-config.php
    regexp="{{ item.regexp }}"
    replace="{{ item.replace }}"
  with_items:
    - { regexp: 'database_name_here', replace: '{{wp_mysql_db}}' }
    - { regexp: 'username_here', replace: '{{wp_mysql_user}}' }
    - { regexp: 'password_here', replace: '{{wp_mysql_password}}'}
  sudo: yes



